### ISSUE TITLE
 oad升级

### ISSUE THREAD

**Issue by TrueloveSomeGIRl** [NoHarry/BLELib#8]
请问下这个oad 升级 怎么写

**Comment by NoHarry** [comment]
> 请问下这个oad 升级 怎么写

oad我没用过，不过我刚才查了下应该就是往一个特征里写升级包，那你可以用下面这种方法
```
    //这个是你先把你的升级包按你的协议分好包
    List<byte[]> dataList=new ArrayList<>();
    WriteData writeData1=new WriteData();
    writeData1.setValue(dataList);
    //这个就是往你的设备的那个特征里写你上面分好包的数据的任务
    WriteTask task1 = Task.newWriteTask(device.getBleDevice(), characteristic, writeData1);
    //执行上面这个任务
    BleAdmin.getINSTANCE(getApplication()).addTask(task1);
```

**Comment by TrueloveSomeGIRl** [comment]
> > 请问下这个oad 升级 怎么写
> 
> oad我没用过，不过我刚才查了下应该就是往一个特征里写升级包，那你可以用下面这种方法
> 
> ```
>     //这个是你先把你的升级包按你的协议分好包
>     List<byte[]> dataList=new ArrayList<>();
>     WriteData writeData1=new WriteData();
>     writeData1.setValue(dataList);
>     //这个就是往你的设备的那个特征里写你上面分好包的数据的任务
>     WriteTask task1 = Task.newWriteTask(device.getBleDevice(), characteristic, writeData1);
>     //执行上面这个任务
>     BleAdmin.getINSTANCE(getApplication()).addTask(task1);
> ```
哦哦  谢了  这个能通过mac 地址链接嘛

**Comment by NoHarry** [comment]
> > > 请问下这个oad 升级 怎么写
> > 
> > 
> > oad我没用过，不过我刚才查了下应该就是往一个特征里写升级包，那你可以用下面这种方法
> > ```
> >     //这个是你先把你的升级包按你的协议分好包
> >     List<byte[]> dataList=new ArrayList<>();
> >     WriteData writeData1=new WriteData();
> >     writeData1.setValue(dataList);
> >     //这个就是往你的设备的那个特征里写你上面分好包的数据的任务
> >     WriteTask task1 = Task.newWriteTask(device.getBleDevice(), characteristic, writeData1);
> >     //执行上面这个任务
> >     BleAdmin.getINSTANCE(getApplication()).addTask(task1);
> > ```
> 
> 哦哦 谢了 这个能通过mac 地址链接嘛

可以通过mac地址搜到设备，然后再连接

**Comment by TrueloveSomeGIRl** [comment]
> > > > 请问下这个oad 升级 怎么写
> > > 
> > > 
> > > oad我没用过，不过我刚才查了下应该就是往一个特征里写升级包，那你可以用下面这种方法
> > > ```
> > >     //这个是你先把你的升级包按你的协议分好包
> > >     List<byte[]> dataList=new ArrayList<>();
> > >     WriteData writeData1=new WriteData();
> > >     writeData1.setValue(dataList);
> > >     //这个就是往你的设备的那个特征里写你上面分好包的数据的任务
> > >     WriteTask task1 = Task.newWriteTask(device.getBleDevice(), characteristic, writeData1);
> > >     //执行上面这个任务
> > >     BleAdmin.getINSTANCE(getApplication()).addTask(task1);
> > > ```
> > 
> > 
> > 哦哦 谢了 这个能通过mac 地址链接嘛
> 
> 可以通过mac地址搜到设备，然后再连接

哦哦 谢了 找了很多库 也改了很多库  只有你这个库在低版本手机上链接很快

**Comment by NoHarry** [comment]
> > > > > 请问下这个oad 升级 怎么写
> > > > 
> > > > 
> > > > oad我没用过，不过我刚才查了下应该就是往一个特征里写升级包，那你可以用下面这种方法
> > > > ```
> > > >     //这个是你先把你的升级包按你的协议分好包
> > > >     List<byte[]> dataList=new ArrayList<>();
> > > >     WriteData writeData1=new WriteData();
> > > >     writeData1.setValue(dataList);
> > > >     //这个就是往你的设备的那个特征里写你上面分好包的数据的任务
> > > >     WriteTask task1 = Task.newWriteTask(device.getBleDevice(), characteristic, writeData1);
> > > >     //执行上面这个任务
> > > >     BleAdmin.getINSTANCE(getApplication()).addTask(task1);
> > > > ```
> > > 
> > > 
> > > 哦哦 谢了 这个能通过mac 地址链接嘛
> > 
> > 
> > 可以通过mac地址搜到设备，然后再连接
> 
> 哦哦 谢了 找了很多库 也改了很多库 只有你这个库在低版本手机上链接很快

哈哈谢谢肯定，如果没其他问题了就麻烦关闭下这个issue啦

**Comment by TrueloveSomeGIRl** [comment]
![9YFZ%YBVTMG)TD3O5@~@7UI](https://user-images.githubusercontent.com/25426589/71155830-925a4c80-2279-11ea-89ca-861f176bf46a.png)
 val writeData = WriteData() //空指针
        writeData.setValue(BaseTool.hexStringToByteArray("09"), true)  
这个为什么为空呢  我连接成功直接去写值， 报这个错误得空指针

**Comment by NoHarry** [comment]
> ![9YFZ%YBVTMG)TD3O5@~@7UI](https://user-images.githubusercontent.com/25426589/71155830-925a4c80-2279-11ea-89ca-861f176bf46a.png)
> val writeData = WriteData() //空指针
> writeData.setValue(BaseTool.hexStringToByteArray("09"), true)
> 这个为什么为空呢 我连接成功直接去写值， 报这个错误得空指针

你可以把Demo跑起来，参考   https://github.com/NoHarry/BLELib/blob/master/app/src/main/java/cc/noharry/bledemo/viewmodel/HomeViewmodel.java#L481    这的用法

**Comment by TrueloveSomeGIRl** [comment]
作者 能加个qq吗  请教些问题

**Comment by NoHarry** [comment]
> 作者 能加个qq吗 请教些问题

453191186
