### ISSUE TITLE
问题请教 

### ISSUE THREAD

**Issue by adftn** [NoHarry/BLELib#9]
为什么 在连接成功的回调里向一个特征写值会报错 我sleep 1s就不 会报错 在写入成功的回调里我去打开通知 也报错 sleep 1s就不 会报错  但是在每个手机上sleep 1s 也会报错 请问有什么解决办法

**Comment by NoHarry** [comment]
> 为什么 在连接成功的回调里向一个特征写值会报错 我sleep 1s就不 会报错 在写入成功的回调里我去打开通知 也报错 sleep 1s就不 会报错 但是在每个手机上sleep 1s 也会报错 请问有什么解决办法

连接成功后需要一段时间才能成功获取到服务，然后才能往服务里的特征写值，所以你最好在　　onServicesDiscovered　　这个回调后在写入

**Comment by adftn** [comment]
> > 为什么 在连接成功的回调里向一个特征写值会报错 我sleep 1s就不 会报错 在写入成功的回调里我去打开通知 也报错 sleep 1s就不 会报错 但是在每个手机上sleep 1s 也会报错 请问有什么解决办法
> 
> 连接成功后需要一段时间才能成功获取到服务，然后才能往服务里的特征写值，所以你最好在　　onServicesDiscovered　　这个回调后在写入
ok 谢了 解决了 但是发现一个问题 在6.0的机子的 总是 133 连接不起

**Comment by NoHarry** [comment]
> > > 为什么 在连接成功的回调里向一个特征写值会报错 我sleep 1s就不 会报错 在写入成功的回调里我去打开通知 也报错 sleep 1s就不 会报错 但是在每个手机上sleep 1s 也会报错 请问有什么解决办法
> > 
> > 
> > 连接成功后需要一段时间才能成功获取到服务，然后才能往服务里的特征写值，所以你最好在　　onServicesDiscovered　　这个回调后在写入
> > ok 谢了 解决了 但是发现一个问题 在6.0的机子的 总是 133 连接不起

133大多数情况是断开时没释放蓝牙资源又去重新连接设备，然后这样多几次就可能出现133然后就一直连不上了，但是重启手机后又会恢复，所以在你用完后你需要自己调用
```
BleAdmin.getINSTANCE(getApplication()).disconnect(bleDevice);
```
这个方法来断开连接，connect和disconnect配对使用能很大程度上避免这个问题的出现
